### ISSUE TITLE
Windows PowerShell和Linux子系统的shell均报错

### ISSUE THREAD

**Issue by leafleave** [linheimx/PyZimuDog#1]
#Windows PowerShell
PS F:\迅雷下载> python F:\迅雷下载\ZimuKu.py
Traceback (most recent call last):
  File "F:\迅雷下载\ZimuKu.py", line 4, in <module>
    from bs4 import Tag
ImportError: No module named 'bs4'
#Linux子系统
root@LOSER:/mnt/f/迅雷下载# python ./ZimuKu.py
  File "./ZimuKu.py", line 11
    def get_RelatedList(keyword: str) -> list:
                               ^
SyntaxError: invalid syntax
请问可能是什么原因？

**Comment by linheimx** [comment]
代码是需要执行环境的
需要：python3
需要：bs4,requests

这玩意目前只是测试，处于玩的目的，以上的模块均未做自动下载。
最近有点忙，木有来得及更新代码，和回复，请见谅。

**Comment by linheimx** [comment]
我想问一下，骚年，你会python吗？

**Comment by linheimx** [comment]
如果你是个学生，我建议你学习下这个玩意

**Comment by linheimx** [comment]
骚年，你会python吗？
如果你是个学生，我建议你学习下这个玩意。

如果你会py，
你也就有能力来爬取字幕网站的能力了，
也就知道我的代码是如何写的了，
也就有可能来维护这个代码喽

**Comment by linheimx** [comment]
可以联系我 QQ：917881222

**Comment by linheimx** [comment]
有兴趣的话，可以联系我。qq：917881222
ps：因为要显示电影，继而显示字幕。命令行交互的方式并不友好
